public with sharing class AIInsightGeneratorService {
  /*
   
   
   Insight Generator
AIInsightGeneratorService.cls
Creates:
AI_Insight__c
records.
Example
AI_Insight__c insight =
    new AI_Insight__c();

insight.Feature_Name__c =
    'Lead Score';

insight.Confidence__c =
    82;

insight.Insight_Text__c =
    'This lead matches partner strengths and recent conversion patterns.';

insight.Recommendation__c =
    'Prioritize this lead.';

insight.Status__c =
    'Generated';
    
    */
}
