import { createElement } from "@lwc/engine-dom";
import NavMenuItems from "c/navMenuItems";

jest.mock("@salesforce/community/basePath", () => ({ default: "/" }), {
  virtual: true
});

describe("c-nav-menu-items", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-nav-menu-items", {
      is: NavMenuItems
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
