public with sharing class AIInsightGeneratorService {
  /*
   
   
   Insight Generator
AIInsightGeneratorService.cls
Creates:
AI_Insight__c
records.
Example
AI_Insight__c insight =
    new AI_Insight__c();

insight.Insight_Type__c =
    'Lead Score';

insight.Score__c =
    leadScore;

insight.Confidence__c =
    82;

insight.Recommendation__c =
    'Prioritize this lead.';

insight.Model_Name__c =
    'PartnerSync Lead Scoring';

insight.Model_Version__c =
    '1.0';
    
    */
}
