public class DealRegistrationLifecycleConstants {
  public static final String SUBMIT = 'Submit Deal';
  public static final String REQUEST_INFORMATION = 'Request Information';
  public static final String RESUBMIT = 'Resubmit Deal';
  public static final String REJECT = 'Reject Registration';
  public static final String CANCEL = 'Cancel Registration';
  public static final String FINALISE_APPROVAL = 'Finalise Deal Approval';
}
